---
name: Check .cabal Consistency

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-consistency:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Save original cabal files
        run: |
          # shellcheck disable=SC2156
          find . -name dist-newstyle -prune -o -type f -name '*.cabal' -exec sh -c \
            "export i={}; grep -v '^--' \"\$i\" | grep -v '^$' > \"\$i.original\"; rm \"\$i\"" \;

      - name: Set up Haskell
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-no-global: true

      - name: Generate .cabal files from package.yaml
        run: stack build --dry-run --no-install-ghc || true

      - name: Save generated cabal file
        run: |
          # shellcheck disable=SC2156
          find . -name dist-newstyle -prune -o -type f -name '*.cabal' -exec sh -c \
            "export i={}; grep -v '^--' \"\$i\" | grep -v '^$' > \"\$i.generated\"" \;

      - name: Print differences
        run: |
          export CORRECT=true
          # shellcheck disable=SC2044
          for i in $(find . -name dist-newstyle -prune -o -type f -name '*.cabal' -print); do \
            if ! diff -u "$i.original" "$i.generated"; then \
              CORRECT=false; \
              continue; \
            fi \
          done
          ${CORRECT}
